#!/bin/sh
#
# Copyright to the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# 
# This script is a wrapper around the "rio" script, and provides the command
# line instruction to start all required Rio services
# (Cybernode, Monitor & Lookup)
# resolve links - $0 may be a soft-link

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

PRG="$0"

while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`/"$link"
    fi
done

DIRNAME=`dirname "$PRG"`
echo $DIRNAMES
SORCER_HOME="$DIRNAME/../../"
cd $SORCER_HOME
SORCER_HOME=`pwd`


install()
{
    echo Installing start script to start SORCER from SORCER_HOME: $SORCER_HOME
    echo "SORCER_HOME=$SORCER_HOME" > /etc/sorcer.conf
    ln -s $SORCER_HOME/configs/start-scripts/sorcer /etc/init.d/sorcer
    if [ -n "$(command -v update-rc.d)" ]; then
        update-rc.d sorcer defaults
    elif [ -n "$(command -v chkconfig)" ]; then
        chkconfig --level 345 sorcer on
    else
      echo "could not set sorcer to autostart with the OS"
    fi
}

uninstall()
{
    echo Uninstalling SORCER start script for SORCER_HOME: $SORCER_HOME
    if [ -n "$(command -v update-rc.d)" ]; then
        update-rc.d -f sorcer remove
    elif [ -n "$(command -v chkconfig)" ]; then
        chkconfig --level 345 sorcer off
    else
      echo "could not uninstall autostarting SORCER with the OS"
    fi
    if [ -f /etc/init.d/sorcer ]; then
        rm /etc/init.d/sorcer
    fi
    if [ -f /etc/sorcer.conf ]; then
        rm /etc/sorcer.conf
    fi
}

if [ "$1" = "-u" ]; then
    uninstall
else
    install
fi
