#!/bin/sh
#
# chkconfig: 2345 50 99
# description: Starts and stops SORCER computing platform
#
### BEGIN INIT INFO
# Provides:          sorcer
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop SORCER platform
# Description:       Provide the SORCER computing platform on this machine                                                                                                                  
### END INIT INFO

# The configuration file /etc/sorcer.conf should exist and contain the following
# variable:
# SORCER_HOME - the location of the Sorcer installation
#
# if a different UNIX user than the owner of SORCER_HOME directory should be used to
# start SORCER specify also the SORCER_USER variable

if [ -f /etc/profile.d/sorcer-env.sh ]; then
  . /etc/profile.d/sorcer-env.sh
fi

if [ -f /etc/sorcer.conf ]; then
  . /etc/sorcer.conf
fi

if [ -z "$SORCER_HOME" ]; then
    echo "SORCER_HOME must be set in /etc/environment or a configuration"
    echo "file (/etc/profile.d/sorcer-env.sh or /etc/sorcer.conf) must exist and contain the SORCER_HOME variable"
    echo "SORCER_HOME must be set in /etc/environment or in the configuration file (/etc/profile.d/sorcer-env.sh /etc/sorcer.conf)" > /tmp/sorcer-starter.log
    exit -1
fi

if [ -z "$JAVA_HOME" ]; then
    echo "JAVA_HOME must be set in /etc/environment or a configuration"
    echo "file (/etc/profile.d/sorcer-env.sh or /etc/sorcer.conf) must exist and contain the JAVA_HOME variable"
    echo "JAVA_HOME must be set in /etc/environment or in the configuration file (/etc/profile.d/sorcer-env.sh or /etc/sorcer.conf)" > /tmp/sorcer-starter.log
    exit -1
fi

if [ -z "$SORCER_USER" ]; then
  SORCER_USER=$(stat -c %U $SORCER_HOME)
fi

if [ -z "$SORCER_PROFILE" ]; then
  SORCER_PROFILE=mix
fi

col=`expr $(tput cols) - 25`
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
NORMAL=$(tput sgr0)

#echo "executing SORCER_STARTER, SH: $SORCER_HOME" > /tmp/sorcer-starter.log
chmod -R a+rwx $SORCER_HOME/logs
chmod -R a+rwx $SORCER_HOME/databases
PID_FILE=$SORCER_HOME/logs/sorcer.pid

do_start()
{
        echo -n " * Starting SORCER..."
        check_status
        if [ ! -f $PID_FILE ]; then
            su -c "$SORCER_HOME/bin/sorcer-boot -w start -Mforce-fork -P$SORCER_PROFILE >  $SORCER_HOME/logs/sorcer-starter.log" $SORCER_USER
	    printf '%s%*s%s' "$GREEN" $col "[ OK ]" "$NORMAL"            
	    echo " "
        else
            echo " SORCER is already running..."
        fi 
}

do_stop()
{
       check_status
       if [ -f $PID_FILE ]; then
            PID=$(cat $PID_FILE);
            echo -n " * Stopping SORCER..."
            kill $PID;
	    printf '%s%*s%s' "$GREEN" $col "[ OK ]" "$NORMAL"            
	    echo " "
            rm $PID_FILE
        else
            echo " SORCER is not running..."
        fi
}

check_status()
{
    if [ -f $PID_FILE ]; then
	PID=$(cat $PID_FILE);
        PS=$(ps aux | grep $PID | grep -v grep);        
        if [ -z "$PS" ]; then	  
	  rm $PID_FILE
	fi
    fi      
}

do_status()
{
    check_status
    if [ -f $PID_FILE ]; then
	echo " SORCER is running"
    else
	echo " SORCER is not running"	  
    fi
}

case $1 in
    start)
      do_start
    ;;
    stop)
      do_stop
    ;;    
    restart)
      do_stop
      do_start
    ;;
    status)
      do_status
    ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit -1
    ;;
esac

exit 0
