#!/bin/bash

# linux and mac
#
export CLASSPATH=${SORCER_HOME}/classes:${SORCER_HOME}/lib/common/jna.jar
export CLASSPATH=$CLASSPATH:${SORCER_HOME}/lib/river/lib/jsk-platform.jar:${SORCER_HOME}/lib/river/lib/jsk-lib.jar
export CLASSPATH=$CLASSPATH:${SORCER_HOME}/lib/rio/rio.jar:${SORCER_HOME}/lib/common/jini-core.jar
export CLASSPATH=$CLASSPATH:${SORCER_HOME}/lib/common/jini-ext.jar:${SORCER_HOME}/lib/common/jep-2.4.1a.jar
export CLASSPATH=$CLASSPATH:${SORCER_HOME}/lib/common/sun-util.jar
export CLASSPATH=$CLASSPATH:${SORCER_HOME}/lib/common/jfreechart/jcommon-1.0.17.jar
export CLASSPATH=$CLASSPATH:${SORCER_HOME}/lib/common/jfreechart/jfreechart-1.0.14.jar

export CLASSPATH=$CLASSPATH:${SORCER_HOME}/../Products/classes

# jre
#
if [ -d $JAVA_HOME ]; then
	export CLASSPATH=$CLASSPATH:$JAVA_HOME/jre/lib/rt.jar
	export CLASSPATH=$CLASSPATH:$JAVA_HOME/jre/lib/resources.jar
fi

# windows
#
#export CLASSPATH_WIN=".:${SORCER_HOME}\classes:${SORCER_HOME}\lib\common\jna.jar:${SORCER_HOME}\lib\river\lib\jsk-platform.jar:${SORCER_HOME}\lib\river\lib\jsk-lib.jar:${SORCER_HOME}\lib\rio\rio.jar:${SORCER_HOME}\lib\common\jini-core.jar:${SORCER_HOME}\lib\common\jini-ext.jar:${SORCER_HOME}\lib\common\jep-2.4.1a.jar:${SORCER_HOME}\lib\common\sun-util.jar"
export CLASSPATH_WIN="$SORCER_HOME\classes;$SORCER_HOME\lib\common\jna.jar;$SORCER_HOME\lib\river\lib\jsk-platform.jar;$SORCER_HOME\lib\river\lib\jsk-lib.jar;$SORCER_HOME\lib\rio\rio.jar;$SORCER_HOME\lib\common\jini-core.jar;$SORCER_HOME\lib\common\jini-ext.jar;$SORCER_HOME\lib\common\jep-2.4.1a.jar;$SORCER_HOME\lib\common\sun-util.jar"

#set CLASSPATH=%SORCER_HOME%\classes;%SORCER_HOME%\lib\common\jna.jar;%SORCER_HOME%\lib\river\lib\jsk-platform.jar;%SORCER_HOME%\lib\river\lib\jsk-lib.jar;%SORCER_HOME%\lib\rio\rio.jar;%SORCER_HOME%\lib\common\jini-core.jar;%SORCER_HOME%\lib\common\jini-ext.jar;%SORCER_HOME%\lib\common\jep-2.4.1a.jar;%SORCER_HOME%\lib\common\sun-util.jar
