#!/bin/bash
#/*
# 
# Copyright 2013 Sorcersoft.com S.A.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# 	http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
#*/
# This script sets the environment needed to run commands in this Sorcer distribution.
#
# Instructions 
# ------------
# Set JAVA_HOME to the location where Java is installed
# Set SORCER_HOME to the directory where Sorcer is installed.
#
# Run this script:
#	$ . setenv.sh
# or
# source ./setenv.sh

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

export SORCER_HOME=$DIR/../
export PATH=$SORCER_HOME/bin:$PATH

if [ -z "$(which mvn)" ]; then
    export MAVEN_HOME=$SORCER_HOME/lib/apache-maven
    export PATH=$MAVEN_HOME/bin:$PATH
fi
if [ -z "$(which ant)" ]; then
    export ANT_HOME=$SORCER_HOME/lib/apache-ant
    export PATH=$ANT_HOME/bin:$PATH
fi

echo "******************************************************************************"
echo "**                       SORCER Examples"
echo "**   SORCER_HOME: $SORCER_HOME"
echo "**"
echo "**   To build and run examples you have to have the following tools installed:"
echo "**"
echo "**   - Java Full JDK (http://java.oracle.com)"
echo "**"
echo "**   When you have them installed and available in your PATH:"
echo "**   1. Source the script to prepare your environment using:"
echo "**      source ./setenv"
echo "**      To set the environment variables permanently add this line to your"
echo "**      .profile, .bashrc or /etc/environment file"
echo "**   2. Before building examples for the first time please run:"
echo "**      ./prepare-repository"
echo "**   3. Then run: mvn install to build the examples."
echo "**   4. If all builds succeed you are ready to go."
echo "**      You can start providers by executing:"
echo "**      boot :ex0-cfg or"
echo "**      boot ex0/ex0-cfg/target/ex0-cfg.jar"
echo "**      or"
echo "**      look for xml ant scripts to start providers"
echo "**      and requestors."
echo "**   5. You can start them by running:"
echo "**      ant -f script.xml"
echo "******************************************************************************"
