#!/bin/bash
#/*
# 
# Copyright 2013 Sorcersoft.com S.A.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# 	http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
#*/
# This script sets the environment needed to run commands in this Sorcer distribution.
#
# Instructions 
# ------------
# Set JAVA_HOME to the location where Java is installed
# Set SORCER_HOME to the directory where Sorcer is installed.
#
# Run this script:
#	$ . setenv.sh
# or
# source ./setenv.sh

export SORCER_HOME=`pwd`/../
export PATH=$SORCER_HOME/bin:$PATH

echo "******************************************************************************"
echo "**                       SORCER Examples"
echo "**   SORCER_HOME: $SORCER_HOME"
echo "**"
echo "**   To build and run examples you have to have the following tools installed:"
echo "**"
echo "**   - Java Full JDK (http://java.oracle.com)"
echo "**   - Apache Maven (http://maven.apache.org)"
echo "**   - Apache Ant (http://ant.apache.org)"
echo "**"
echo "**   When you have them installed and available in your PATH:"
echo "**   1. Source the script to prepare your environment using:"
echo "**      source ./setenv"
echo "**   2. Before building examples for the first time please run:"
echo "**      ant -f prepare-repository.xml"
echo "**   3. Then run: mvn install to build the examples."
echo "**   4. If all builds succeed you are ready to go."
echo "**      Please look for xml ant scripts to start providers and requestors."
echo "**   5. You can start them by running:"
echo "**      ant -f script.xml"
echo "**"
echo "**"
echo "******************************************************************************"
