#!/bin/bash

# linux and mac
#
export CLASSPATH=${IGRID_HOME}/classes:${IGRID_HOME}/lib/common/jna.jar
export CLASSPATH=$CLASSPATH:${IGRID_HOME}/lib/river/lib/jsk-platform.jar:${IGRID_HOME}/lib/river/lib/jsk-lib.jar
export CLASSPATH=$CLASSPATH:${IGRID_HOME}/lib/rio/rio.jar:${IGRID_HOME}/lib/common/jini-core.jar
export CLASSPATH=$CLASSPATH:${IGRID_HOME}/lib/common/jini-ext.jar:${IGRID_HOME}/lib/common/jep-2.4.1a.jar
export CLASSPATH=$CLASSPATH:${IGRID_HOME}/lib/common/sun-util.jar
export CLASSPATH=$CLASSPATH:${IGRID_HOME}/lib/common/jfreechart/jcommon-1.0.17.jar
export CLASSPATH=$CLASSPATH:${IGRID_HOME}/lib/common/jfreechart/jfreechart-1.0.14.jar

export CLASSPATH=$CLASSPATH:${IGRID_HOME}/../Products/classes

# jre
#
if [ -d $JAVA_HOME ]; then
	export CLASSPATH=$CLASSPATH:$JAVA_HOME/jre/lib/rt.jar
	export CLASSPATH=$CLASSPATH:$JAVA_HOME/jre/lib/resources.jar
fi

# windows
#
#export CLASSPATH_WIN=".:${IGRID_HOME}\classes:${IGRID_HOME}\lib\common\jna.jar:${IGRID_HOME}\lib\river\lib\jsk-platform.jar:${IGRID_HOME}\lib\river\lib\jsk-lib.jar:${IGRID_HOME}\lib\rio\rio.jar:${IGRID_HOME}\lib\common\jini-core.jar:${IGRID_HOME}\lib\common\jini-ext.jar:${IGRID_HOME}\lib\common\jep-2.4.1a.jar:${IGRID_HOME}\lib\common\sun-util.jar"
export CLASSPATH_WIN="$IGRID_HOME\classes;$IGRID_HOME\lib\common\jna.jar;$IGRID_HOME\lib\river\lib\jsk-platform.jar;$IGRID_HOME\lib\river\lib\jsk-lib.jar;$IGRID_HOME\lib\rio\rio.jar;$IGRID_HOME\lib\common\jini-core.jar;$IGRID_HOME\lib\common\jini-ext.jar;$IGRID_HOME\lib\common\jep-2.4.1a.jar;$IGRID_HOME\lib\common\sun-util.jar"

#set CLASSPATH=%IGRID_HOME%\classes;%IGRID_HOME%\lib\common\jna.jar;%IGRID_HOME%\lib\river\lib\jsk-platform.jar;%IGRID_HOME%\lib\river\lib\jsk-lib.jar;%IGRID_HOME%\lib\rio\rio.jar;%IGRID_HOME%\lib\common\jini-core.jar;%IGRID_HOME%\lib\common\jini-ext.jar;%IGRID_HOME%\lib\common\jep-2.4.1a.jar;%IGRID_HOME%\lib\common\sun-util.jar
